#lista de caminos para las que tienen url completa y fecha
def lista_caminos_fc():
    caminos = ['//html/body/div/div/div/div/div/div/div/article/h2/a',
                '//div/article/h2[@class="post-title"]/a[@rel="bookmark"]',
                '//div/div/div/div/h3/a',
                '//div/header/h2/a',
                '//html/body/div/div[2]/div/div[2]/div[2]/div/div/div/div/h2/a',
                '//*[@id="post-139"]/div/h2/a',
                '//tr/td/span/a',
                '//div/div/div/div[2]/h5/a',
                '//div/div/div/h3/a',
                '//div/div/div/div/div/div/div/div/h3/a',
                '//*[@id="main"]/div/div/div/section/h4/a',
                '//div[@class="loop"]/div/div/a',
                '//div[@class="article-content-wrap"]/div[@class="post-header"]/h2/a',
                '//section[@class="main-content left"]/section/div/article/div[2]/div/h3/a',
                '//*/div/div/div/div/div/div/div/h3/a',
                '/html/body/div/main/section/div/div/div/div[2]/div/article/a[2]',
                '//section[@class="home-section latest-posts"]/div/article/header/h2/a',
                '/html/body/div/div/div/section/div/div/div/div/div/div/div/div/article/div/div/h3/a',
                '//div[@id="omc-container"]/section[@id="omc-main"]/article/a',
                '//section[@class="main container"]/div/section[@class="content"]/section/article/h2/a',
                '//div[@class="contenedor"]/main[@class="principal"]/section/div/div/div[1]/article/div[1]/h2/a',
                '//div[@class="loop"]/div[1]/div/div/h3/a',
                '//div/div/div/div[@class="post-title"]/a',
                '//div[@id="posts"]/div/article/div[3]/h2/a',
                '//div[@id="posts"]/div/article/div[3]/h2/a',
                '//div[@id="level1"]/div[2]/div/h3/a',
                '//section[@id="primary"]/div/article/header/h1/a',
                '//div[@id="wraper"]/div[@id="container"]/div[@id="content"]/div/a',
                '//div[@class="col-12 col-sm-6 col-md-4"]/div/div[@class="card-body"]/h3[@class="card-title"]/a',
                '//section[@class="headlines"]/div[@class="container"]/div[2]/div/article/a',
                '//div[@class="MainBlock"]/div/article/header/h2/a',
                '//div[@class="page"]/div[@class="content"]/div[3]/div[1]/a',
                '//body/div[@id="site-wrap"]/div[@class="archive-wrap section__beauty"]/div[1]/div/div/h4/a',
                '//*[@id="col-AB"]/span/span/article/span/h1/a',
                '//ul[@id="results-content"]/li[@style="clear:left"]/h2/a',
                '//*[@id="col-AB"]/span/span/article/span/h1/a',
                '//div[@class="row-widget-wrap left relative"]/ul[@class="row-widget-list"]/li/a',
                '//div[@id="main"]/div[@class="container feature"]/div[@class="post_list"]/ul/li/a',
                '//*[@id="content-archive"]/ul/li/div/h4/a',
                '//*[@id="content"]/div/div/div/div/div/div/div/h3/a',
                '//*[@id="editorial_page"]/section/div[2]/ul/li/article/div/div/h2/a',
                '//div[@class="l-container"]/div/article/div[2]/h2/a',
                '//*[@class="SectionPage-main"]/div/div/div/div[1]/ps-list-loadmore/ul/li/div/div/div[2]/a',
                '//section[@class="main-features"]/div/div/div[2]/div/h2/a',
                '//*[@class="clearfix"]/div[@id="container"]/div[@id="content"]/article/header/h2/a',
                '//div[@class="td-block-span6"]/div/h3/a',
                '//div[@class="td-block-span6"]/div/h3/a',
                '//div[@class="td-block-span6"]/div/h3/a',
                '//div[@class="td-block-span6"]/div/h3/a',
                '//div[@class="td-block-span6"]/div/h3/a',
                '//div[@class="td-block-span6"]/div/h3/a',
                '//div[@class="views-element-container"]/div/div/article/div/div[2]/div/div/a',
                '//div[@role="main"]/div[2]/section/div[@class="row posts"]/ul/li/article/div[@class="row"]/div[2]/h2/a',
                '//div[@role="main"]/div[2]/section/div[@class="row posts"]/ul/li/article/div[@class="row"]/div[2]/h2/a',
                '//div[@class="blog_custom"]/div[2]/div/h3/a',
                '//div[@class="row"]/div[1]/div/div[@class="post-info"]/h2/a',
                '//div[@class="landingrow"]/div/div/div/h2/a',
                '//div[@id="content"]/div[2]/div/div[1]/div[2]/article/div[2]/h2[@class="entry-title h5"]/a',
                '//div[@role="main"]/div/div/div[@class="item-details"]/h3/a',
                '//*[@id="content-archive"]/ul/li/div[@class="media-body"]/h4/a',
                '//*[@id="penci-archive__content"]/div[2]/article/div/div[2]/header/h2/a',
                '//*[@id="content"]/section/div[2]/div[@class="anti-gutter"]/div/article/div[@class="block-lead"]/h2/a',
                '//div[1]/div[1]/div/div/main/section/div[@class="section-recent"]/div/div/article/div[2]/header/h2[@class="abstract-title"]/a',
                '//*[@id="us_grid_0"]/div/article/div/h2/a']
    return caminos
