#lista de caminos para las que no tienen fecha
def lista_caminos_nf():
    caminos = ['//*[@id="post-10709"]/div/div[1]/div/div[1]/div/div[2]/section/article/div[2]/h4/a',
                '//section[@id="mainpagecontent"]/section/article/a[2]',
                '//tr/td[2]/a',
                '//h2[@class="entry-title"]/a',
                '//*[@id="content"]/div/h3/a',
                '//div/div/article/a',
                '//div[@class="taxonomy-detail-lists box1"]/div/article/div[2]/h2/a',
                '//*[@id="td-outer-wrap"]/div/div/div/div[1]/div/div/div/div/div/h3/a',
                '//div[@id="content_container_50872"]/div[@class="news-grid"]/a[@class="col-lg-3 col-md-4 col-sm-6 col-xs-12 news"]',
                '//div[@class="column size-1of1"]/article/div[2]/h2/a[@class="et-accent-color"]',
                '//*[@id="listings"]/div/article/div/div/h4/a',
                '//section[@id="content"]/div/div[1]/article/div[3]/h2/a',
                '//div[@class="content"]/div[3]/div[@class="layout--sticky"]/div/div/section[1]/div[3]/div/article/div/a',
                '/html/body/div[2]/div[3]/div/div[1]/div/section[1]/div[2]/div[1]/article/div/div/h3/a',
                '//*[@class="container"]/ul[@class="clearfix"]/li/a',
                '//div[@class="mmenu-placeholder"]/div[2]/div[@id="section-2"]/div[2]/div/article/div[1]/a',
                '//div[@class="records"]/article/div[2]/h2[@class="headline article-summary__headline"]/a',
                '//div[@class="no class"]/div/div/div/div/div/div/section/div/aside/div/div[2]/div[2]/div/a',
                '//div[@class="content"]/div[@class="views-element-container"]/div/div/div[1]/div[1]/a',
                '//div[@class="contentList"]/div[@class="itemList"]/div/h3/a',
                '//div[@class="publication_outer_grid"]/div/div/div/div[2]/div/a',
                '//div/main[@id="content"]/div[@class="wrapper"]/div/div/div/section/a',
                '//*[@id="content_wrapper"]/div/div[2]/div[2]/div[2]/div/div/div[2]/a',
                '//*[@id="section-2"]/div[2]/div[1]/article/div[2]/h2/a',
                '//*[@id="section-2"]/div[2]/div[1]/article/div[@class="article-summary__details has-image"]/h2/a',
                '//div[@class="box1 article-topic"]/div[@class="records"]/article/div[2]/h2/a',
                '//div[@id="homeContentGroup"]/div/div/div[2]/h3/a',
                '//div[@class="records"]/article/div[2]/h2/a',
                '//div[@class="records"]/article/div[2]/h2[@class="headline article-summary__headline"]/a',
                '//*[@id="section-2"]/div[2]/div[@class="records"]/article/div/h2/a',
                '//*[@id="block-supplychaindigital-content"]/div/div/div/div/div/div[2]/div/h3/a',
                '//*[@class="boxesList"]/li/div/div[2]/div/div/div/div/div/div/div/div/div/div/div[1]/div[2]/div/div/div/div/div/div/div/div/div/div/h4/a',
                '//div[4]/div/div/div[@class="main-inner"]/div[@class="post-list"]/article/h2/a',
                '//article/div[2]/section/div/div[@role="list"]/div/a',
                '//section/div/div/div[1]/div/div/h3[@class="entry-title"]/a',
                '//div[2]/div/div[2]/div/div/div/div[1]/div[2]/div[@class="row "]/div/div[@class="card"]/div[1]/a',
                '//main[@class="main"]/div[2]/div[2]/article/header/h2/a',
                '//main/section/div/div[2]/div/article/a']
    return caminos	
