# lista de dominios para las paginas de noticias que no tienen fecha.
def lista_dominios_nf():
    dominios=['http://energyandmines.com',
                'http://news.top-consultant.com',
                'http://www.blackseagrain.net',
                'http://www.cadenadesuministro.es',
                'http://www.itnewsafrica.com',
                'http://www.petromindo.com',
                'http://www.safetyandhealthmagazine.com',
                'http://www.textileworld.com',
                'https://creative.vic.gov.au',
                'https://dispositivosmedicos.org.mx',
                'https://innovation.ox.ac.uk',
                'https://revistadelogistica.com',
                'https://www.9news.com.au',
                'https://www.9news.com',
                'https://www.adu.com',
                'https://www.architecturalrecord.com',
                'https://www.bevindustry.com',
                'https://www.bsigroup.com',
                'https://www.constructionglobal.com',
                'https://www.cosmeticsandtoiletries.com',
                'https://www.creativeindustriesfederation.com',
                'https://www.edie.net',
                'https://www.envapack.com',
                'https://www.flexpackmag.com',
                'https://www.foodbusinessnews.net',
                'https://www.foodengineeringmag.com',
                'https://www.gcimagazine.com',
                'https://www.ishn.com',
                'https://www.packagingstrategies.com',
                'https://www.supplychainbrain.com',
                'https://www.supplychaindigital.com',
                'https://www.textilescotland.com',
                'https://www.themanufacturer.com',
                'https://www.thinkwithgoogle.com',
                'https://www.tourism-review.com',
                'https://www.uruguayxxi.gub.uy',
                'https://www.wasteprousa.com',
                'https://www.screenskills.com']

    return dominios