#lista de urls iniciales para las que no tienen fecha
def lista_urls_nf():
    urls = [#'http://energyandmines.com',
            'http://news.top-consultant.com/uk/newsheadlines.aspx',
            'http://www.blackseagrain.net/news/world?b_start:int=',
            'http://www.cadenadesuministro.es/category/noticias/logistica',
            'http://www.itnewsafrica.com/category/industries/energy_news',
            'http://www.petromindo.com/?table=news&pos=global',
            'http://www.safetyandhealthmagazine.com/topics/99-news?page=',
            'http://www.textileworld.com/category/textile-world/breaking-news',
            'https://creative.vic.gov.au/news',
            'https://dispositivosmedicos.org.mx/noticias/',
            'https://innovation.ox.ac.uk/innovation-news/all-news',
            'https://revistadelogistica.com/category/ultimas-noticias/',
            'https://www.9news.com.au/government/',
            'https://www.9news.com.au/transport/2',
            'https://www.adu.com/blog/page/',
            'https://www.architecturalrecord.com/articles/topic/91?page=',
            'https://www.bevindustry.com/articles/topic/2642?page=',
            'https://www.bsigroup.com/en-GB/blog/Medical-Device-Blog/',
            'https://www.constructionglobal.com/?page=',
            'https://www.cosmeticsandtoiletries.com/networking/news/?page=',
            'https://www.creativeindustriesfederation.com/our-news',
            'https://www.edie.net/news/index.asp',
            'https://www.envapack.com',
            'https://www.flexpackmag.com/articles/topic/2712?page=',
            'https://www.foodbusinessnews.net/articles/topic/96?page=',
            'https://www.foodengineeringmag.com/articles/topic/15089-news?page=',
            'https://www.gcimagazine.com',
            'https://www.ishn.com/articles/topic/4282-news?page=',
            'https://www.packagingstrategies.com/articles/topic/3007-news?page=',
            'https://www.supplychainbrain.com/articles/topic/1148?page=',
            'https://www.supplychaindigital.com/?page=',
            'https://www.textilescotland.com/industry-news?pg=',
            'https://www.themanufacturer.com/articletype/news',
            'https://www.thinkwithgoogle.com/consumer-insights/',
            'https://www.tourism-review.com/top-weekly-travel-news/',
            'https://www.uruguayxxi.gub.uy/en/news/ano-2018/creative-industries-1',
            'https://www.wasteprousa.com/news',
            'https://www.screenskills.com/']
    return urls	
